export const GETLEADERBOARDDATA = {
	users: [
		{
			id: 3,
			name: 'Megan',
			teams: [17, 18, 19, 20, 21, 22, 23, 24],
			matchedTeams: [
				{
					id: 17,
					name: 'Lions',
					wins: 11,
					losses: 4,
					playoffBerth: true,
					conference: 'NFC',
					division: 'North',
					divisionWinner: true,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 21,
				},
				{
					id: 18,
					name: 'Dolphins',
					wins: 11,
					losses: 4,
					playoffBerth: true,
					conference: 'AFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 16,
				},
				{
					id: 19,
					name: 'Chargers',
					wins: 5,
					losses: 10,
					playoffBerth: false,
					conference: 'AFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 5,
				},
				{
					id: 20,
					name: 'Browns',
					wins: 10,
					losses: 5,
					playoffBerth: false,
					conference: 'AFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 10,
				},
				{
					id: 21,
					name: 'Giants',
					wins: 5,
					losses: 10,
					playoffBerth: false,
					conference: 'NFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 5,
				},
				{
					id: 22,
					name: 'Packers',
					wins: 7,
					losses: 8,
					playoffBerth: false,
					conference: 'NFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 7,
				},
				{
					id: 23,
					name: 'Buccaneers',
					wins: 8,
					losses: 7,
					playoffBerth: false,
					conference: 'NFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 24,
					name: 'Commanders',
					wins: 4,
					losses: 11,
					playoffBerth: false,
					conference: 'NFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 4,
				},
			],
			totalScore: 76,
			rank: 1,
		},
		{
			id: 1,
			name: 'Alec',
			teams: [1, 2, 3, 4, 5, 6, 7, 8],
			matchedTeams: [
				{
					id: 1,
					name: 'Eagles',
					wins: 11,
					losses: 4,
					playoffBerth: true,
					conference: 'NFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 16,
				},
				{
					id: 2,
					name: 'Bengals',
					wins: 8,
					losses: 7,
					playoffBerth: false,
					conference: 'AFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 3,
					name: 'Jaguars',
					wins: 8,
					losses: 7,
					playoffBerth: false,
					conference: 'AFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 4,
					name: 'Vikings',
					wins: 7,
					losses: 8,
					playoffBerth: false,
					conference: 'NFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 7,
				},
				{
					id: 5,
					name: 'Bears',
					wins: 6,
					losses: 9,
					playoffBerth: false,
					conference: 'NFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 6,
				},
				{
					id: 6,
					name: 'Steelers',
					wins: 8,
					losses: 7,
					playoffBerth: false,
					conference: 'AFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 7,
					name: 'Colts',
					wins: 8,
					losses: 7,
					playoffBerth: false,
					conference: 'AFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 8,
					name: 'Texans',
					wins: 8,
					losses: 7,
					playoffBerth: false,
					conference: 'AFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
			],
			totalScore: 69,
			rank: 2,
		},
		{
			id: 2,
			name: 'Brad',
			teams: [9, 10, 11, 12, 13, 14, 15, 16],
			matchedTeams: [
				{
					id: 9,
					name: 'Chiefs',
					wins: 9,
					losses: 6,
					playoffBerth: false,
					conference: 'AFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 9,
				},
				{
					id: 10,
					name: '49ers',
					wins: 11,
					losses: 4,
					playoffBerth: true,
					conference: 'NFC',
					division: 'West',
					divisionWinner: true,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 21,
				},
				{
					id: 11,
					name: 'Saints',
					wins: 7,
					losses: 8,
					playoffBerth: false,
					conference: 'NFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 7,
				},
				{
					id: 12,
					name: 'Seahawks',
					wins: 8,
					losses: 7,
					playoffBerth: false,
					conference: 'NFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 13,
					name: 'Broncos',
					wins: 7,
					losses: 8,
					playoffBerth: false,
					conference: 'AFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 7,
				},
				{
					id: 14,
					name: 'Falcons',
					wins: 7,
					losses: 8,
					playoffBerth: false,
					conference: 'NFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 7,
				},
				{
					id: 15,
					name: 'Titans',
					wins: 5,
					losses: 10,
					playoffBerth: false,
					conference: 'AFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 5,
				},
				{
					id: 16,
					name: 'Cardinals',
					wins: 3,
					losses: 12,
					playoffBerth: false,
					conference: 'NFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 3,
				},
			],
			totalScore: 67,
			rank: 3,
		},
		{
			id: 4,
			name: 'Nic',
			teams: [25, 26, 27, 28, 29, 30, 31, 32],
			matchedTeams: [
				{
					id: 25,
					name: 'Bills',
					wins: 9,
					losses: 6,
					playoffBerth: false,
					conference: 'AFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 9,
				},
				{
					id: 26,
					name: 'Cowboys',
					wins: 10,
					losses: 5,
					playoffBerth: true,
					conference: 'NFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 15,
				},
				{
					id: 27,
					name: 'Jets',
					wins: 6,
					losses: 9,
					playoffBerth: false,
					conference: 'AFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 6,
				},
				{
					id: 28,
					name: 'Ravens',
					wins: 11,
					losses: 3,
					playoffBerth: true,
					conference: 'AFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 16,
				},
				{
					id: 29,
					name: 'Raiders',
					wins: 6,
					losses: 8,
					playoffBerth: false,
					conference: 'AFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 6,
				},
				{
					id: 30,
					name: 'Patriots',
					wins: 3,
					losses: 11,
					playoffBerth: false,
					conference: 'AFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 3,
				},
				{
					id: 31,
					name: 'Panthers',
					wins: 2,
					losses: 13,
					playoffBerth: false,
					conference: 'NFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 2,
				},
				{
					id: 32,
					name: 'Rams',
					wins: 8,
					losses: 7,
					playoffBerth: false,
					conference: 'NFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
			],
			totalScore: 65,
			rank: 4,
		},
	],
};

export const GETALLUSERDATA = {
	users: [
		{ id: 1, name: 'Alec', teams: [1, 2, 3, 4, 5, 6, 7, 8] },
		{ id: 2, name: 'Brad', teams: [9, 10, 11, 12, 13, 14, 15, 16] },
		{ id: 3, name: 'Megan', teams: [17, 18, 19, 20, 21, 22, 23, 24] },
		{ id: 4, name: 'Nic', teams: [25, 26, 27, 28, 29, 30, 31, 32] },
	],
};

export const GETSCORINGDATA = {
	win: 1,
	playoffBerth: 5,
	divisionWinner: 5,
	superbowlBerth: 10,
	superbowlWin: 5,
};
