export const GETLEADERBOARDDATA = {
	users: [
		{
			id: 3,
			name: 'Megan',
			teams: [17, 18, 19, 20, 21, 22, 23, 24],
			matchedTeams: [
				{
					id: 17,
					name: 'Lions',
					wins: 11,
					losses: 5,
					playoffBerth: true,
					conference: 'NFC',
					division: 'North',
					divisionWinner: true,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 21,
				},
				{
					id: 18,
					name: 'Dolphins',
					wins: 11,
					losses: 5,
					playoffBerth: true,
					conference: 'AFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 16,
				},
				{
					id: 19,
					name: 'Chargers',
					wins: 5,
					losses: 11,
					playoffBerth: false,
					conference: 'AFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 5,
				},
				{
					id: 20,
					name: 'Browns',
					wins: 11,
					losses: 5,
					playoffBerth: true,
					conference: 'AFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 16,
				},
				{
					id: 21,
					name: 'Giants',
					wins: 5,
					losses: 11,
					playoffBerth: false,
					conference: 'NFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 5,
				},
				{
					id: 22,
					name: 'Packers',
					wins: 8,
					losses: 8,
					playoffBerth: false,
					conference: 'NFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 23,
					name: 'Buccaneers',
					wins: 8,
					losses: 8,
					playoffBerth: false,
					conference: 'NFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 24,
					name: 'Commanders',
					wins: 4,
					losses: 12,
					playoffBerth: false,
					conference: 'NFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 4,
				},
			],
			totalScore: 83,
			rank: 1,
		},
		{
			id: 2,
			name: 'Brad',
			teams: [9, 10, 11, 12, 13, 14, 15, 16],
			matchedTeams: [
				{
					id: 9,
					name: 'Chiefs',
					wins: 10,
					losses: 6,
					playoffBerth: true,
					conference: 'AFC',
					division: 'West',
					divisionWinner: true,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 20,
				},
				{
					id: 10,
					name: '49ers',
					wins: 12,
					losses: 4,
					playoffBerth: true,
					conference: 'NFC',
					division: 'West',
					divisionWinner: true,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 22,
				},
				{
					id: 11,
					name: 'Saints',
					wins: 8,
					losses: 8,
					playoffBerth: false,
					conference: 'NFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 12,
					name: 'Seahawks',
					wins: 8,
					losses: 8,
					playoffBerth: false,
					conference: 'NFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 13,
					name: 'Broncos',
					wins: 8,
					losses: 8,
					playoffBerth: false,
					conference: 'AFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 14,
					name: 'Falcons',
					wins: 7,
					losses: 9,
					playoffBerth: false,
					conference: 'NFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 7,
				},
				{
					id: 15,
					name: 'Titans',
					wins: 5,
					losses: 11,
					playoffBerth: false,
					conference: 'AFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 5,
				},
				{
					id: 16,
					name: 'Cardinals',
					wins: 4,
					losses: 12,
					playoffBerth: false,
					conference: 'NFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 4,
				},
			],
			totalScore: 82,
			rank: 2,
		},
		{
			id: 4,
			name: 'Nic',
			teams: [25, 26, 27, 28, 29, 30, 31, 32],
			matchedTeams: [
				{
					id: 25,
					name: 'Bills',
					wins: 10,
					losses: 6,
					playoffBerth: false,
					conference: 'AFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 10,
				},
				{
					id: 26,
					name: 'Cowboys',
					wins: 11,
					losses: 5,
					playoffBerth: true,
					conference: 'NFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 16,
				},
				{
					id: 27,
					name: 'Jets',
					wins: 6,
					losses: 10,
					playoffBerth: false,
					conference: 'AFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 6,
				},
				{
					id: 28,
					name: 'Ravens',
					wins: 13,
					losses: 3,
					playoffBerth: true,
					conference: 'AFC',
					division: 'North',
					divisionWinner: true,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 23,
				},
				{
					id: 29,
					name: 'Raiders',
					wins: 6,
					losses: 9,
					playoffBerth: false,
					conference: 'AFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 6,
				},
				{
					id: 30,
					name: 'Patriots',
					wins: 4,
					losses: 12,
					playoffBerth: false,
					conference: 'AFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 4,
				},
				{
					id: 31,
					name: 'Panthers',
					wins: 2,
					losses: 14,
					playoffBerth: false,
					conference: 'NFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 2,
				},
				{
					id: 32,
					name: 'Rams',
					wins: 9,
					losses: 7,
					playoffBerth: true,
					conference: 'NFC',
					division: 'West',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 14,
				},
			],
			totalScore: 81,
			rank: 3,
		},
		{
			id: 1,
			name: 'Alec',
			teams: [1, 2, 3, 4, 5, 6, 7, 8],
			matchedTeams: [
				{
					id: 1,
					name: 'Eagles',
					wins: 11,
					losses: 5,
					playoffBerth: true,
					conference: 'NFC',
					division: 'East',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 16,
				},
				{
					id: 2,
					name: 'Bengals',
					wins: 8,
					losses: 8,
					playoffBerth: false,
					conference: 'AFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 8,
				},
				{
					id: 3,
					name: 'Jaguars',
					wins: 9,
					losses: 7,
					playoffBerth: false,
					conference: 'AFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 9,
				},
				{
					id: 4,
					name: 'Vikings',
					wins: 7,
					losses: 9,
					playoffBerth: false,
					conference: 'NFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 7,
				},
				{
					id: 5,
					name: 'Bears',
					wins: 7,
					losses: 9,
					playoffBerth: false,
					conference: 'NFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 7,
				},
				{
					id: 6,
					name: 'Steelers',
					wins: 9,
					losses: 7,
					playoffBerth: false,
					conference: 'AFC',
					division: 'North',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 9,
				},
				{
					id: 7,
					name: 'Colts',
					wins: 9,
					losses: 7,
					playoffBerth: false,
					conference: 'AFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 9,
				},
				{
					id: 8,
					name: 'Texans',
					wins: 9,
					losses: 7,
					playoffBerth: false,
					conference: 'AFC',
					division: 'South',
					divisionWinner: false,
					superbowlBerth: false,
					superbowlWin: false,
					totalScore: 9,
				},
			],
			totalScore: 74,
			rank: 4,
		},
	],
};

export const GETALLUSERDATA = {
	users: [
		{ id: 1, name: 'Alec', teams: [1, 2, 3, 4, 5, 6, 7, 8] },
		{ id: 2, name: 'Brad', teams: [9, 10, 11, 12, 13, 14, 15, 16] },
		{ id: 3, name: 'Megan', teams: [17, 18, 19, 20, 21, 22, 23, 24] },
		{ id: 4, name: 'Nic', teams: [25, 26, 27, 28, 29, 30, 31, 32] },
	],
};

export const GETSCORINGDATA = {
	win: 1,
	playoffBerth: 5,
	divisionWinner: 5,
	superbowlBerth: 10,
	superbowlWin: 5,
};

export const GETSEASONDATA = {
	teams: [
		{
			id: 1,
			name: 'Eagles',
			wins: 11,
			losses: 5,
			playoffBerth: true,
			conference: 'NFC',
			division: 'East',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 2,
			name: 'Bengals',
			wins: 8,
			losses: 8,
			playoffBerth: false,
			conference: 'AFC',
			division: 'North',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 3,
			name: 'Jaguars',
			wins: 9,
			losses: 7,
			playoffBerth: false,
			conference: 'AFC',
			division: 'South',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 4,
			name: 'Vikings',
			wins: 7,
			losses: 9,
			playoffBerth: false,
			conference: 'NFC',
			division: 'North',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 5,
			name: 'Bears',
			wins: 7,
			losses: 9,
			playoffBerth: false,
			conference: 'NFC',
			division: 'North',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 6,
			name: 'Steelers',
			wins: 9,
			losses: 7,
			playoffBerth: false,
			conference: 'AFC',
			division: 'North',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 7,
			name: 'Colts',
			wins: 9,
			losses: 7,
			playoffBerth: false,
			conference: 'AFC',
			division: 'South',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 8,
			name: 'Texans',
			wins: 9,
			losses: 7,
			playoffBerth: false,
			conference: 'AFC',
			division: 'South',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 9,
			name: 'Chiefs',
			wins: 10,
			losses: 6,
			playoffBerth: true,
			conference: 'AFC',
			division: 'West',
			divisionWinner: true,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 10,
			name: '49ers',
			wins: 12,
			losses: 4,
			playoffBerth: true,
			conference: 'NFC',
			division: 'West',
			divisionWinner: true,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 11,
			name: 'Saints',
			wins: 8,
			losses: 8,
			playoffBerth: false,
			conference: 'NFC',
			division: 'South',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 12,
			name: 'Seahawks',
			wins: 8,
			losses: 8,
			playoffBerth: false,
			conference: 'NFC',
			division: 'West',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 13,
			name: 'Broncos',
			wins: 8,
			losses: 8,
			playoffBerth: false,
			conference: 'AFC',
			division: 'West',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 14,
			name: 'Falcons',
			wins: 7,
			losses: 9,
			playoffBerth: false,
			conference: 'NFC',
			division: 'South',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 15,
			name: 'Titans',
			wins: 5,
			losses: 11,
			playoffBerth: false,
			conference: 'AFC',
			division: 'South',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 16,
			name: 'Cardinals',
			wins: 4,
			losses: 12,
			playoffBerth: false,
			conference: 'NFC',
			division: 'West',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 17,
			name: 'Lions',
			wins: 11,
			losses: 5,
			playoffBerth: true,
			conference: 'NFC',
			division: 'North',
			divisionWinner: true,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 18,
			name: 'Dolphins',
			wins: 11,
			losses: 5,
			playoffBerth: true,
			conference: 'AFC',
			division: 'East',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 19,
			name: 'Chargers',
			wins: 5,
			losses: 11,
			playoffBerth: false,
			conference: 'AFC',
			division: 'West',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 20,
			name: 'Browns',
			wins: 11,
			losses: 5,
			playoffBerth: true,
			conference: 'AFC',
			division: 'North',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 21,
			name: 'Giants',
			wins: 5,
			losses: 11,
			playoffBerth: false,
			conference: 'NFC',
			division: 'East',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 22,
			name: 'Packers',
			wins: 8,
			losses: 8,
			playoffBerth: false,
			conference: 'NFC',
			division: 'North',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 23,
			name: 'Buccaneers',
			wins: 8,
			losses: 8,
			playoffBerth: false,
			conference: 'NFC',
			division: 'South',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 24,
			name: 'Commanders',
			wins: 4,
			losses: 12,
			playoffBerth: false,
			conference: 'NFC',
			division: 'East',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 25,
			name: 'Bills',
			wins: 10,
			losses: 6,
			playoffBerth: false,
			conference: 'AFC',
			division: 'East',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 26,
			name: 'Cowboys',
			wins: 11,
			losses: 5,
			playoffBerth: true,
			conference: 'NFC',
			division: 'East',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 27,
			name: 'Jets',
			wins: 6,
			losses: 10,
			playoffBerth: false,
			conference: 'AFC',
			division: 'East',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 28,
			name: 'Ravens',
			wins: 13,
			losses: 3,
			playoffBerth: true,
			conference: 'AFC',
			division: 'North',
			divisionWinner: true,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 29,
			name: 'Raiders',
			wins: 6,
			losses: 9,
			playoffBerth: false,
			conference: 'AFC',
			division: 'West',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 30,
			name: 'Patriots',
			wins: 4,
			losses: 12,
			playoffBerth: false,
			conference: 'AFC',
			division: 'East',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 31,
			name: 'Panthers',
			wins: 2,
			losses: 14,
			playoffBerth: false,
			conference: 'NFC',
			division: 'South',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
		{
			id: 32,
			name: 'Rams',
			wins: 9,
			losses: 7,
			playoffBerth: true,
			conference: 'NFC',
			division: 'West',
			divisionWinner: false,
			superbowlBerth: false,
			superbowlWin: false,
		},
	],
};
